package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
)

const generatedHeader = "// Code generated by phonesafe-gen. DO NOT EDIT.\n\n"

// emitMetadata generates metadata_gen.go with RegionMetadata, NonGeoMetadata,
// CountryCodeToRegions, and NANPARegions.
func emitMetadata(territories []parsedTerritory, outDir string) error {
	// Validate all regex patterns first.
	for _, t := range territories {
		if err := validateTerritoryPatterns(t); err != nil {
			return fmt.Errorf("territory %s: %w", t.ID, err)
		}
	}

	// Separate into region vs non-geo.
	var regionTerritories []parsedTerritory
	var nonGeoTerritories []parsedTerritory
	for _, t := range territories {
		if t.ID == "001" {
			nonGeoTerritories = append(nonGeoTerritories, t)
		} else {
			regionTerritories = append(regionTerritories, t)
		}
	}

	// Sort for determinism.
	sort.Slice(regionTerritories, func(i, j int) bool {
		return regionTerritories[i].ID < regionTerritories[j].ID
	})
	sort.Slice(nonGeoTerritories, func(i, j int) bool {
		return nonGeoTerritories[i].CountryCode < nonGeoTerritories[j].CountryCode
	})

	// Build CountryCodeToRegions and NANPARegions.
	ccToRegions := make(map[int32][]string)
	mainCountry := make(map[int32]string)
	for _, t := range regionTerritories {
		ccToRegions[t.CountryCode] = append(ccToRegions[t.CountryCode], t.ID)
		if t.MainCountryForCode {
			mainCountry[t.CountryCode] = t.ID
		}
	}
	// Sort regions within each country code: main country first, then alphabetical.
	for cc, regions := range ccToRegions {
		main := mainCountry[cc]
		sort.Slice(regions, func(i, j int) bool {
			if regions[i] == main {
				return true
			}
			if regions[j] == main {
				return false
			}
			return regions[i] < regions[j]
		})
		ccToRegions[cc] = regions
	}

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package metadata\n\n")

	// RegionMetadata
	buf.WriteString("// RegionMetadata maps CLDR region code to phone metadata.\n")
	buf.WriteString("var RegionMetadata = map[string]*PhoneMetadata{\n")
	for _, t := range regionTerritories {
		emitTerritoryLiteral(&buf, t)
	}
	buf.WriteString("}\n\n")

	// NonGeoMetadata
	buf.WriteString("// NonGeoMetadata maps country calling code to metadata for non-geographical entities.\n")
	buf.WriteString("var NonGeoMetadata = map[int32]*PhoneMetadata{\n")
	for _, t := range nonGeoTerritories {
		fmt.Fprintf(&buf, "\t%d: ", t.CountryCode)
		emitMetadataStruct(&buf, t)
		buf.WriteString(",\n")
	}
	buf.WriteString("}\n\n")

	// CountryCodeToRegions
	buf.WriteString("// CountryCodeToRegions maps a calling code to all regions sharing it.\n")
	buf.WriteString("var CountryCodeToRegions = map[int32][]string{\n")
	ccs := sortedInt32Keys(ccToRegions)
	for _, cc := range ccs {
		fmt.Fprintf(&buf, "\t%d: {", cc)
		for i, r := range ccToRegions[cc] {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%q", r)
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("}\n\n")

	// NANPARegions
	buf.WriteString("// NANPARegions is the set of regions in the North American Numbering Plan.\n")
	buf.WriteString("var NANPARegions = map[string]struct{}{\n")
	nanpa := ccToRegions[1]
	sort.Strings(nanpa)
	for _, r := range nanpa {
		fmt.Fprintf(&buf, "\t%q: {},\n", r)
	}
	buf.WriteString("}\n")

	return writeFormatted(filepath.Join(outDir, "metadata_gen.go"), buf.Bytes())
}

// emitShortMetadata generates shortmetadata_gen.go.
func emitShortMetadata(territories []parsedShortTerritory, outDir string) error {
	// Validate patterns.
	for _, t := range territories {
		if err := validateDescPattern(t.GeneralDesc, "GeneralDesc", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.TollFree, "TollFree", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.StandardRate, "StandardRate", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.PremiumRate, "PremiumRate", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.CarrierSpecific, "CarrierSpecific", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.Emergency, "Emergency", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.ExpandedEmergency, "ExpandedEmergency", t.ID); err != nil {
			return err
		}
		if err := validateDescPattern(t.SMSServices, "SMSServices", t.ID); err != nil {
			return err
		}
	}

	sort.Slice(territories, func(i, j int) bool {
		return territories[i].ID < territories[j].ID
	})

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package metadata\n\n")

	buf.WriteString("// ShortMetadata maps CLDR region code to short number metadata.\n")
	buf.WriteString("var ShortMetadata = map[string]*ShortPhoneMetadata{\n")
	for _, t := range territories {
		fmt.Fprintf(&buf, "\t%q: {\n", t.ID)
		emitDescField(&buf, "GeneralDesc", t.GeneralDesc)
		emitDescField(&buf, "TollFree", t.TollFree)
		emitDescField(&buf, "StandardRate", t.StandardRate)
		emitDescField(&buf, "PremiumRate", t.PremiumRate)
		emitDescField(&buf, "CarrierSpecific", t.CarrierSpecific)
		emitDescField(&buf, "Emergency", t.Emergency)
		emitDescField(&buf, "ExpandedEmergency", t.ExpandedEmergency)
		emitDescField(&buf, "SMSServices", t.SMSServices)
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	return writeFormatted(filepath.Join(outDir, "shortmetadata_gen.go"), buf.Bytes())
}

// emitAlternateFormats generates alternateformats_gen.go.
func emitAlternateFormats(formats []parsedAltFormats, outDir string) error {
	// Validate patterns.
	for _, af := range formats {
		for _, f := range af.Formats {
			if f.Pattern != "" {
				if _, err := regexp.Compile(f.Pattern); err != nil {
					return fmt.Errorf("country code %d: invalid pattern %q: %w", af.CountryCode, f.Pattern, err)
				}
			}
		}
	}

	sort.Slice(formats, func(i, j int) bool {
		return formats[i].CountryCode < formats[j].CountryCode
	})

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package metadata\n\n")

	buf.WriteString("// AlternateFormats maps country calling code to alternate formatting patterns.\n")
	buf.WriteString("var AlternateFormats = map[int32][]NumberFormat{\n")
	for _, af := range formats {
		fmt.Fprintf(&buf, "\t%d: {\n", af.CountryCode)
		for _, f := range af.Formats {
			emitFormatLiteral(&buf, f, "\t\t")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	return writeFormatted(filepath.Join(outDir, "alternateformats_gen.go"), buf.Bytes())
}

// emitGeocoding generates geocoding_gen.go.
func emitGeocoding(data map[string][]geoEntry, outDir string) error {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package data\n\n")

	buf.WriteString("// GeoData maps BCP 47 language code to sorted prefix-to-description entries.\n")
	buf.WriteString("var GeoData = map[string][]GeoEntry{\n")

	// Sort languages.
	langs := make([]string, 0, len(data))
	for lang := range data {
		langs = append(langs, lang)
	}
	sort.Strings(langs)

	for _, lang := range langs {
		entries := data[lang]
		fmt.Fprintf(&buf, "\t%q: {\n", lang)
		for _, e := range entries {
			fmt.Fprintf(&buf, "\t\t{%d, %q},\n", e.Prefix, e.Description)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	return writeFormatted(filepath.Join(outDir, "geocoding_gen.go"), buf.Bytes())
}

// emitTimezones generates timezones_gen.go.
func emitTimezones(data []tzEntry, outDir string) error {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package data\n\n")

	buf.WriteString("// TimezoneData is a sorted slice of prefix-to-timezone mappings.\n")
	buf.WriteString("var TimezoneData = []TZEntry{\n")
	for _, e := range data {
		fmt.Fprintf(&buf, "\t{%d, []string{", e.Prefix)
		for i, tz := range e.TimeZones {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%q", tz)
		}
		buf.WriteString("}},\n")
	}
	buf.WriteString("}\n")

	return writeFormatted(filepath.Join(outDir, "timezones_gen.go"), buf.Bytes())
}

// --- Helpers ---

func emitTerritoryLiteral(buf *bytes.Buffer, t parsedTerritory) {
	fmt.Fprintf(buf, "\t%q: ", t.ID)
	emitMetadataStruct(buf, t)
	buf.WriteString(",\n")
}

func emitMetadataStruct(buf *bytes.Buffer, t parsedTerritory) {
	buf.WriteString("&PhoneMetadata{\n")
	fmt.Fprintf(buf, "\t\tID: %q,\n", t.ID)
	fmt.Fprintf(buf, "\t\tCountryCode: %d,\n", t.CountryCode)
	if t.InternationalPrefix != "" {
		fmt.Fprintf(buf, "\t\tInternationalPrefix: %q,\n", t.InternationalPrefix)
	}
	if t.PreferredInternationalPrefix != "" {
		fmt.Fprintf(buf, "\t\tPreferredInternationalPrefix: %q,\n", t.PreferredInternationalPrefix)
	}
	if t.NationalPrefix != "" {
		fmt.Fprintf(buf, "\t\tNationalPrefix: %q,\n", t.NationalPrefix)
	}
	if t.PreferredExtnPrefix != "" {
		fmt.Fprintf(buf, "\t\tPreferredExtnPrefix: %q,\n", t.PreferredExtnPrefix)
	}
	if t.NationalPrefixForParsing != "" {
		fmt.Fprintf(buf, "\t\tNationalPrefixForParsing: %q,\n", t.NationalPrefixForParsing)
	}
	if t.NationalPrefixTransformRule != "" {
		fmt.Fprintf(buf, "\t\tNationalPrefixTransformRule: %q,\n", t.NationalPrefixTransformRule)
	}
	if t.MainCountryForCode {
		buf.WriteString("\t\tMainCountryForCode: true,\n")
	}
	if t.LeadingDigits != "" {
		fmt.Fprintf(buf, "\t\tLeadingDigits: %q,\n", t.LeadingDigits)
	}
	if t.MobileNumberPortable {
		buf.WriteString("\t\tMobileNumberPortable: true,\n")
	}

	emitDescField(buf, "GeneralDesc", t.GeneralDesc)
	emitDescField(buf, "FixedLine", t.FixedLine)
	emitDescField(buf, "Mobile", t.Mobile)
	emitDescField(buf, "TollFree", t.TollFree)
	emitDescField(buf, "PremiumRate", t.PremiumRate)
	emitDescField(buf, "SharedCost", t.SharedCost)
	emitDescField(buf, "PersonalNumber", t.PersonalNumber)
	emitDescField(buf, "VOIP", t.VOIP)
	emitDescField(buf, "Pager", t.Pager)
	emitDescField(buf, "UAN", t.UAN)
	emitDescField(buf, "Voicemail", t.Voicemail)
	emitDescField(buf, "NoInternationalDialling", t.NoInternationalDialling)

	if len(t.NumberFormats) > 0 {
		buf.WriteString("\t\tNumberFormats: []NumberFormat{\n")
		for _, f := range t.NumberFormats {
			emitFormatLiteral(buf, f, "\t\t\t")
		}
		buf.WriteString("\t\t},\n")
	}
	if len(t.IntlNumberFormats) > 0 {
		buf.WriteString("\t\tIntlNumberFormats: []NumberFormat{\n")
		for _, f := range t.IntlNumberFormats {
			emitFormatLiteral(buf, f, "\t\t\t")
		}
		buf.WriteString("\t\t},\n")
	}

	buf.WriteString("\t}")
}

func emitDescField(buf *bytes.Buffer, name string, d parsedDesc) {
	if d.NationalNumberPattern == "" && len(d.PossibleLengths) == 0 && d.ExampleNumber == "" {
		return
	}
	fmt.Fprintf(buf, "\t\t%s: PhoneNumberDesc{\n", name)
	if d.NationalNumberPattern != "" {
		fmt.Fprintf(buf, "\t\t\tNationalNumberPattern: %q,\n", d.NationalNumberPattern)
	}
	if len(d.PossibleLengths) > 0 {
		buf.WriteString("\t\t\tPossibleLengths: []int32{")
		for i, l := range d.PossibleLengths {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%d", l)
		}
		buf.WriteString("},\n")
	}
	if len(d.PossibleLengthsLocal) > 0 {
		buf.WriteString("\t\t\tPossibleLengthsLocal: []int32{")
		for i, l := range d.PossibleLengthsLocal {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%d", l)
		}
		buf.WriteString("},\n")
	}
	if d.ExampleNumber != "" {
		fmt.Fprintf(buf, "\t\t\tExampleNumber: %q,\n", d.ExampleNumber)
	}
	buf.WriteString("\t\t},\n")
}

func emitFormatLiteral(buf *bytes.Buffer, f parsedFormat, indent string) {
	fmt.Fprintf(buf, "%s{\n", indent)
	fmt.Fprintf(buf, "%s\tPattern: %q,\n", indent, f.Pattern)
	fmt.Fprintf(buf, "%s\tFormat: %q,\n", indent, f.Format)
	if len(f.LeadingDigitsPatterns) > 0 {
		fmt.Fprintf(buf, "%s\tLeadingDigitsPatterns: []string{", indent)
		for i, ld := range f.LeadingDigitsPatterns {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", ld)
		}
		buf.WriteString("},\n")
	}
	if f.NationalPrefixFormattingRule != "" {
		fmt.Fprintf(buf, "%s\tNationalPrefixFormattingRule: %q,\n", indent, f.NationalPrefixFormattingRule)
	}
	if f.NationalPrefixOptional {
		fmt.Fprintf(buf, "%s\tNationalPrefixOptional: true,\n", indent)
	}
	if f.DomesticCarrierCodeFormattingRule != "" {
		fmt.Fprintf(buf, "%s\tDomesticCarrierCodeFormattingRule: %q,\n", indent, f.DomesticCarrierCodeFormattingRule)
	}
	if f.IntlFormat != "" {
		fmt.Fprintf(buf, "%s\tIntlFormat: %q,\n", indent, f.IntlFormat)
	}
	fmt.Fprintf(buf, "%s},\n", indent)
}

func validateTerritoryPatterns(t parsedTerritory) error {
	descs := []struct {
		name string
		desc parsedDesc
	}{
		{"GeneralDesc", t.GeneralDesc},
		{"FixedLine", t.FixedLine},
		{"Mobile", t.Mobile},
		{"TollFree", t.TollFree},
		{"PremiumRate", t.PremiumRate},
		{"SharedCost", t.SharedCost},
		{"PersonalNumber", t.PersonalNumber},
		{"VOIP", t.VOIP},
		{"Pager", t.Pager},
		{"UAN", t.UAN},
		{"Voicemail", t.Voicemail},
		{"NoInternationalDialling", t.NoInternationalDialling},
	}
	for _, d := range descs {
		if err := validateDescPattern(d.desc, d.name, t.ID); err != nil {
			return err
		}
	}
	for i, f := range t.NumberFormats {
		if f.Pattern != "" {
			if _, err := regexp.Compile(f.Pattern); err != nil {
				return fmt.Errorf("format[%d] pattern %q: %w", i, f.Pattern, err)
			}
		}
	}
	return nil
}

func validateDescPattern(d parsedDesc, name, territory string) error {
	if d.NationalNumberPattern == "" {
		return nil
	}
	if _, err := regexp.Compile(d.NationalNumberPattern); err != nil {
		return fmt.Errorf("territory %s %s pattern %q: %w", territory, name, d.NationalNumberPattern, err)
	}
	return nil
}

func writeFormatted(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		// Write unformatted for debugging.
		_ = os.WriteFile(path+".raw", src, 0o644)
		return fmt.Errorf("formatting %s: %w", filepath.Base(path), err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func sortedInt32Keys(m map[int32][]string) []int32 {
	keys := make([]int32, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	return keys
}

