// Code generated by phonesafe-gen. DO NOT EDIT.
// Source: libphonenumber v8.13.50

package metadata

// UpstreamVersion is the libphonenumber version this metadata was generated from.
const UpstreamVersion = "v8.13.50"
